kontakt_capture = ('Hallo! Ich heiße Georgij. Ich bin ein Hochzeitsfotograf für Kaarst, Neuss, Düsseldorf, Köln, '
                   'Bonn und ganz Deutschland. Ich wohne in Kaarst, aber ich liebe es, zu reisen, und komme gerne zu Ihrer '
                   'Hochzeit egal wohin. Überall in Deutschland und auf der ganzen Welt.\n\nIch glaube, dass die Hochzeit vor allem ein Fest mit den '
                   'Freunden und Verwandten ist, und es ist eigentlich unmöglich, diesen Tag zu wiederholen. Ich versuche, zeitlose'
                   ' Fotos zu machen, damit man sie mit den Kindern und Enkeln viele Jahre später noch anschauen und genießen kann.'
                   ' Dabei ist mein Ziel, den ganzen Prozess möglichst angenehm, schön und aufrichtig zu gestalten.\n\n'
                   'Wenn Euch meine Bilder gefallen und ihr auf der Suche nach einem <a href="https://shugol.com">'
                   'Hochzeitfotograf</a>, '
                   'dann schreibt mir auf WhatsApp. Ich werde mich so schnell wie möglich bei Ihnen melden.\n\n'
                   'Tel., WhatsApp:  +49 152 22090552\n\n'
                   'Meine <a href="https://telegra.ph/Shugol-video-07-09">Siege in Wettbewerben und auch kurzen Video</a>\n\n'
                   'Auch können Sie durch diesen Bot ein Nachricht schiken,\n nach drücken   /kontaktiere\n\n'
                   '/back')

text_for_kontakt = ('Bitte shreiben Sie in Ihrem nächsten Beitrag Ihre Nachricht')

success_send = 'Ihre Nachricht wurde erfolgreich versendet!'

waiting_15 = 'Sie können in 15 Minuten fortfahren'

just_waitng = 'Warten Sie bitte am bisschen !'

faq = ('<b><i>FRAGEN & ANTWORTEN</i></b>\n\n<b>Wie lange dauert die hohczeitreportage ?</b>\n'
       'Vieles hängt von Ihren Wünschen und des Tagesplanes ab, doch in der Regel ca. 8-13 Stunden.\n\n'
       '<b>Fotografieren Sie an anderen Orten und welche kosten dabei anfallen</b>?\n'
       'Ich lebe in Kaarst und bin natürlich sehr viel in dieser Region unterwegs, '
       'doch komme gerne deutschlandweit, um Sie mit Kamera zu begleiten. Anreise innerhalb Deutschlands ist im eventuellen '
       'Paket-Preis inbegriffen\n\n'
       '<b>Wie viele Hochzeitsbilder werden wir erhalten ?</b>\n'
       'Je nach Anzahl der Stunden erhalten Sie ca. 400 – 800 gut fotografierte Bilder.\n\n'
       '<b>Bearbeiten Sie alle geschossenen Hochzeitsbilder ?</b>\n'
       'Ja, ich bearbeite alle Bilder. Besuchen Sie meinen Internet-Auftritt, um Einblick darin zu bekommen.\n\n'
       '<b>Wie schnell liefern Sie Ihre Fotos ab ?</b>\n'
       'Sie erhalten Ihre Fotos innerhalb von 2-6 Wochen nach der Hochzeit, je nach Jahreszeit.\n\n'
       '<b>Ab wann genau vor der Hochzeit, können wir Sie als Fotografen buchen?</b>\n'
       'Meistens wird 6-12 Monate vor der Hochzeit gebucht, aber wenn der gewünschte Zeitraum frei ist, können Sie'
       ' mich jederzeit buchen.\n\n'
       '<b>Wie kann man ein Foto-Termin vereinbaren ?</b>\n'
       'Wir unterzeichnen einen Vertrag, nach Erhalt der Rechnung leisten Sie Vorauszahlung, und nun bin ich als Fotograf für Sie da.\n\n'
       '<b>Welche Ausrüstung nutzen Sie ?</b>\n'
       'Ich benutze die Nikon-Berufsausrüstung (Vollformat) mit mehreren Profi-Objektiven, die der Phantasie des '
       'Hochzeitsfotografen einen freien Lauf auf dem höchsten technischen Niveau lassen.\n\n'
       '<b>Was passiert, wenn eine Kamera am Hochzeitstag kaputtgeht ?</b>\n'
       'Bei der Aufnahme ist immer die Ersatzausrüstung (Vollformat-Kamera und Objektiven) schussbereit, so '
       'können Sie sicher sein, dass selbst bei einem ungeplanten Ausfall der Technik das Schießen weiter geht.\nAußerdem '
       'werden alle Fotos auf der zweiten Speicherkarte kopiert.\n\n'
       ''
       '<b>Erstellen sie Fotobücher?</b>\n'
       'Ich glaube, dass Hochzeitsfotobücher die Ergebnisse zur Geltung am besten bringen. Aus meiner Sicht ist '
       'ein hochwertiges Hochzeitsbuch ideal, um auf Jahre hinaus wahre Liebesgeschichten, die so während eines einzigen '
       'Hochzeitstages erzählt werden, in Fotos aufzubewahren.\n'
       'Ich kann Ihnen verschiedene Formate und Design-Ideen anbieten.\n\n'
       '<b>Wie kann man mich erreichen ?</b>\n'
       'Sie können mir eine Mail über das Kontaktformular senden, in WhatsApp schreiben oder mich telefonisch erreichen.\n'
       'Ich freue mich immer von Ihnen zu hören!\n\n'
       '/back')

preise = ('<b><i>LEISTUNGEN UND PREIS</i></b>\n\n'
          'Zu meinen Dienstleistungen gehört sowohl das Fotografieren der Registrierung im Standesamt als auch die Trauung in der'
          ' Kirche oder eine Registrierung auswärts.\n\n'
          'Hochzeitsreportagen fotografiere ich in ganz Deutschland und Weltweit.\n\n'
          'Ich biete verschiedene Hochzeitspakete an\n(ab 180 Euro pro Stunde ).\n\n'
          'Kontaktiert mich für Euer individuelles Angebot.\n\n'
          'Egal, für was Ihr Euch entscheidet, grundsätzlich ist immer folgendes enthalten:\n\n'
          '- Hochzeits reportage Eurer Hochzeit\n'
          '- Hochzeitsvorbereitung, Trauung, Gruppen fotos, Paarshooting, Feierfotos\n'
          '- Nachbearbeitung, Auswahl und Optimierung der Fotos\n'
          '- Alle Fotos sind hochaufgelöst, ohne Logo und ohne Wasserzeichen\n'
          '- Ausgewählten Fotos auf einem USB-Stick\n'
          '- Eine passwortgeschütze Online-Galerie für Sie und Ihre Gäste (8 Wochen)\n'
          '- Fahrtkosten innerhalb Deutschland\n\n'
          '<b>Standesamtliche Hochzeit</b>\n'
          'Sie können ein Fotoshooting der Registrierung im Standesamt ab 2 Stunden bestellen.\n\n'
          '<b>Engagement Shooting:</b>\n'
          'Engagement-Shooting ist ein hervorragendes Training vor dem Fotoshooting während der Hochzeit. So lernen Sie den '
          'Fotografen besser kennen und gewöhnen sich daran, vor der Kamera zu stehen. Der Fotograf wird sich seinerseits die '
          'besten Blickwinkel für Ihr Fotoshooting merken und diese später umsetzen. Fotos von so einem Fotoshooting passen '
          'hervorragend, um daraus Hochzeitseinladungen zu machen.\n\n'
          '<b>After Wedding Shooting:</b>\n'
          'Wenn das Wetter am Tag Ihrer Hochzeit schlecht war oder Sie keine Zeit für ein Portraitfoto hatten, können Sie ein '
          'Fotoshooting nach der Hochzeit bestellen. In einer ruhigen Umgebung, zu einer passenden Tageszeit, an irgendeinem'
          ' besonders schönen Ort, wo sie am Tag Ihrer Hochzeit nicht hinkommen könnten, verbringen wir 2-3 Stunden mit dem '
          'Schießen der Fotos und am Ende bekommen Sie hervorragende Hochzeitsportraits.\n\n'
          '<b>Hochzeitsalben:</b>\n'
          'Die Zeit, wo ein Fotoalbum mit gedruckten Fotos gefüllt wurde, ist schon längst vorbei. Jetzt schauen wir uns die '
          'Fotos in sozialen Netzwerken an und speichern sie auf unserem Computer. Das drucken von großen Fotostapeln ist '
          'mittlerweile Geschichte, aber man kann nicht abstreiten, dass es manchmal doch noch angenehm ist, ein echtes Fotoalbum '
          'mit den liebsten Bildern in der Hand zu halten. Ich biete Ihnen das Drucken und die Gestaltung von exklusiven Fotobuch '
          'mit ausgewählten Fotos von Ihrer Hochzeit an.\n\n'
          'Interesse geweckt? Kontaktiert mich durch Bot oder WhatsApp, um mehr zu erfahren.\n\n/back'
          )

bookmark_add = 'Foto zu Lesezeichen hinzugefügt !'

bookmark_10 = 'Sie können bis zu 10 verschiedene Fotos hinzufügen'

no_bookmarks = ('Sie haben noch keine Lesezeichen.\n\n '
                'Um eine Foto zu Ihren Lesezeichen hinzuzufügen, '
                'klicken Sie beim Seen eines Buches auf die mitte Schaltfläche '
                )

bookmark_list = '<b>Eure Lesezeichen:</b>               ❤️'

cancel = ('zurück kommen')

edit_bookmarks_button = 'Lesezeichen bearbeiten'

edit_bookmarks = 'löschen nutzloss Lesezeichen'

help_answer = ('<b>Anweisungen</b>\n\n\n'
               'Verfügbare Befehle:\n\n'
               '/slide_show - sehen Sleiden\n\n'
               '/bookmarks - Lesezeichen anzeigen\n\n'
               '/menu  -  zurück zum grund INFO\n\n'
               'Um ein Lesezeichen zu speichern, klicken Sie auf die'
               '  Schaltfläche mit der Seitenzahl\n\n'
               '/kontakt  - shreiben mir Nachricht durch Bot\n\n'
               '<b>Viel Spaß beim Lesen!</b>')

echo = 'Dieser Kommand ist mir nicht klar.\n\nListe der verfügbaren Kommande im Menü oder in der /help'
